title: Xuanming Cui
author: Xuanming Cui
# url: "https://ankitsultana.com"
# baseurl: "/researcher"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Template from Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Google scholar"
   link: "https://scholar.google.com/citations?user=2tpwyb4AAAAJ&hl=en"
 - name: "Github"
   link: "https://github.com/xuanmingcui"
 - name: "Linkedin"
   link: "https://www.linkedin.com/in/xuanming-cui-9686b9170/"
 - name: "Blog"
   link: "https://xuanmingcui.me/"
